In [ ]:
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library 
import numpy as np
import cmath

#The algorithm was implmented and adapted from article LU Decomposition in Python and NumPy, found in the refrences. 

(A) = np.array([ [1/cmath.sqrt(2), 1/cmath.sqrt(2), 1/cmath.sqrt(2), -1/cmath.sqrt(2)], [3, -8, 1, cmath.sqrt(-3)], [-1, 1, 4, cmath.sqrt(-5)], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)  

#np.isnan(A).any() 
np.isinf(A).any()

print("A:")
print(A)

print("P:")
pprint.pprint(P) 

print("L:")
pprint.pprint(L) 

print ("U:")
pprint.pprint(U)

A:
[[ 0.70710678+0.j          0.70710678+0.j          0.70710678+0.j
  -0.70710678+0.j        ]
 [ 3.        +0.j         -8.        +0.j          1.        +0.j
   0.        +1.73205081j]
 [-1.        +0.j          1.        +0.j          4.        +0.j
   0.        +2.23606798j]
 [ 2.        +0.j         -4.        +0.j         -1.        +0.j
   6.        +0.j        ]]
P:
array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
L:
array([[ 1.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.23570226+0.j,  1.        +0.j,  0.        +0.j,
         0.        +0.j],
       [-0.33333333+0.j, -0.64282435+0.j,  1.        +0.j,
         0.        +0.j],
       [ 0.66666667+0.j,  0.51425948+0.j, -0.41176471+0.j,
         1.        +0.j]])
U:
array([[ 3.        +0.j        , -8.        +0.j        ,
         1.        +0.j        ,  0.        +1.73205081j],
       [ 0.        +0.j        ,  2.59272486+0.j        

In [ ]:
import pprint

def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""

    # Converts N into a list of tuples of columns                                                                                                                                                                                                      
    tuple_N = zip(*N)

    # Nested list comprehension to calculate matrix multiplication                                                                                                                                                                                     
    return [[sum(el_m * el_n for el_m, el_n in zip(row_m, col_n)) for col_n in tuple_N] for row_m in M]

def pivot_matrix(M):
    """Returns the pivoting matrix for M, used in Doolittle's method."""
    m = len(M)

    # Create an identity matrix, with floating point values                                                                                                                                                                                            
    id_mat = [[float(i ==j) for i in range(m)] for j in range(m)]

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of of M                                                                                                                                                                                               
    for j in range(m):
        row = max(range(j, m), key=lambda i: abs(M[i][j]))
        if j != row:
            # Swap the rows                                                                                                                                                                                                                            
            id_mat[j], id_mat[row] = id_mat[row], id_mat[j]

    return id_mat

def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # Create zero matrices for L and U                                                                                                                                                                                                                 
    L = [[0.0] * n for i in range(n)]
    U = [[0.0] * n for i in range(n)]

    # Create the pivot matrix P and the multipled matrix PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = mult_matrix(P, A)

    # Perform the LU Decomposition                                                                                                                                                                                                                     
    for j in range(n):
        # All diagonal entries of L are set to unity                                                                                                                                                                                                   
        L[j][j] = 1.0

        # LaTeX: u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}                                                                                                                                                                                      
        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = PA[i][j] - s1

        # LaTeX: l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )                                                                                                                                                                  
        for i in range(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            L[i][j] = (PA[i][j] - s2) / U[j][j]

    return (P, L, U)


A = ([ [1/cmath.sqrt(2), 1/cmath.sqrt(2), 1/cmath.sqrt(2), -1/cmath.sqrt(2)], [3, -8, 1, cmath.sqrt(-3)], [-1, 1, 4, cmath.sqrt(-5)], [2, -4, -1, 6] ])
print (A[0])
print (A[1])
print (A[2])
print (A[3])
# #print (A[4])
# #print (A[5])
# #print (A[6])
# print (A[7])
# print (A[8])
# print (A[9])
# print (A[10])
# print (A[11])
# print (A[12])
# print (A[13])
# print (A[14])
# print (A[15])

print ("A:")
pprint.pprint(A)

print ("P:")
pprint.pprint(P)

print ("L:")
pprint.pprint(L)

print ("U:")
pprint.pprint(U)

[(0.7071067811865475+0j), (0.7071067811865475+0j), (0.7071067811865475+0j), (-0.7071067811865475+0j)]
[3, -8, 1, 1.7320508075688772j]
[-1, 1, 4, 2.23606797749979j]
[2, -4, -1, 6]
A:
[[(0.7071067811865475+0j),
  (0.7071067811865475+0j),
  (0.7071067811865475+0j),
  (-0.7071067811865475+0j)],
 [3, -8, 1, 1.7320508075688772j],
 [-1, 1, 4, 2.23606797749979j],
 [2, -4, -1, 6]]
P:
array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
L:
array([[ 1.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.23570226+0.j,  1.        +0.j,  0.        +0.j,
         0.        +0.j],
       [-0.33333333+0.j, -0.64282435+0.j,  1.        +0.j,
         0.        +0.j],
       [ 0.66666667+0.j,  0.51425948+0.j, -0.41176471+0.j,
         1.        +0.j]])
U:
array([[ 3.        +0.j        , -8.        +0.j        ,
         1.        +0.j        ,  0.        +1.73205081j],
       [ 0.        +0.j        ,  2.59272486+0.j        ,